### PR TITLE
Make script to prepare dataset

### PR DESCRIPTION
**Pull request by SpeedOfMagic**
This commits changes the following:
1. Adds script to convert dataset from its format to format, where there are only two columns "input" and "output"
2. Moves dataset-specific code to this script

### CODE REVIEW

**Review by IINemo — COMMENTED** [review]
Please, change the name of the script to polygraph_prepare_dataset

**Comment by SpeedOfMagic** [comment]
add to benchmark section how to use datasets

**Comment by rvashurin** [comment]
@SpeedOfMagic can we close this PR since we are already going with another approach?

**Comment by SpeedOfMagic** [comment]
OK

**Pull request closed without merging**
