### PR TITLE
Allow project to be uploaded to pypi

### PR DESCRIPTION
**Pull request by SpeedOfMagic**
1. Added pyproject.toml, which is required to upload project
2. Removed setup.py, since it is replaced by pyproject.toml
3. Made lazy deberta setup, since right now ```import lm_polygraph``` downloads 1.2G model

Resulting page: https://test.pypi.org/project/lm-polygraph/0.0.2.dev0/
https://pypi.org/project/lm-polygraph/

### CODE REVIEW

**Comment by rvashurin** [comment]
Need to add https://setuptools.pypa.io/en/latest/userguide/entry_point.html to `pyproject.toml` to expose our executable scripts.

**Comment by SpeedOfMagic** [comment]
> Need to add https://setuptools.pypa.io/en/latest/userguide/entry_point.html to pyproject.toml to expose our executable scripts.

Done

**Comment by rvashurin** [comment]
@SpeedOfMagic can you also check that installing of LM Polygraph into clean environment succeeds and produces a working installation - i.e. all executable scripts are accessible and tests pass?

**Comment by SpeedOfMagic** [comment]
> @SpeedOfMagic can you also check that installing of LM Polygraph into clean environment succeeds and produces a working installation - i.e. all executable scripts are accessible and tests pass?

Done, everything seems fine to me

**Review by IINemo — APPROVED** [review]

**Pull request merged**
