### PR TITLE
Prepare datasets

### PR DESCRIPTION
**Pull request by SpeedOfMagic**
This commits changes the following:

1. Creates dataset builder from dataset's format to format, where there are only two columns "input" and "output"
2. Moves dataset-specific code to this builder (only for xsum, aeslc, trivia_qa_tiny)
3. Edits test config to use this builder

### CODE REVIEW

**Comment by rvashurin** [comment]
This is a step in the right direction I think, but we need to consider this further. This had to cover all the datasets in our benchmark: CoQA, TriviaQA, MMLU, GSM8K, XSum, WMT14, WMT19, claim-level bench. 

Next, if we want to use datasets from HF directly, that already have properly formatted input and output, for all of the above (except claim level) we need to consider several versions with different prompts: one for foundation models, and possibly several for verbalized uncertainty estimation for instruct models (see PR #221 for exact prompts).

I would also argue, that we need to have a separate builder script and dataset page on HF for each of the described cases (or at least for each base dataset, with configurable prompt). 

Another thing that we have to consider is the need for unprocessed data from the base dataset. I.e. for PTrue, when we want to ask model about the confidence, we better insert original question from TriviaQA, for example, instead of the whole prompt.

@ArtemVazh @IINemo @SpeedOfMagic

**Comment by SpeedOfMagic** [comment]
> I would also argue, that we need to have a separate builder script and dataset page on HF for each of the described cases (or at least for each base dataset, with configurable prompt).

That's probably not a very good idea, because, since each huggingface dataset is a separate repo, a lot of code will be duplicated between different datasets.

I'll try to do other stuff.

**Comment by rvashurin** [comment]
> > I would also argue, that we need to have a separate builder script and dataset page on HF for each of the described cases (or at least for each base dataset, with configurable prompt).
> 
> That's probably not a very good idea, because, since each huggingface dataset is a separate repo, a lot of code will be duplicated between different datasets.
> 
> I'll try to do the other stuff.

I think only thing that's going to be duplicated is boilerplate HF builder code, dataset-specific code will probably be different. What's important here is that if user will want to get his own dataset into the same format, it's going to be easier to just clone builder script for a specific dataset and adjust it, than to figure out complicated `if-elif-else` stuff in single builder script for all dataset.

**Comment by rvashurin** [comment]
BTW can you convert this to draft PR for the time being? @SpeedOfMagic

**Comment by SpeedOfMagic** [comment]
> I think only thing that's going to be duplicated is boilerplate HF builder code, and that's ok

Boilerplate dataset code has about 70 LoC. If we apply it to 16 datasets (as of in main), we get 70 * 15 = 1050 LoC that could
ve been removed.

> dataset-specific code will probably be different

There are four datasets (trivia_qa_tiny, aeslc, gsm8k, xsum) that have the same logic, three WMT datasets and four person datasets, so dataset-specific code will also be duplicated.

> What's important here is that if user will want to get his own dataset into the same format, it's going to be easier to just clone builder script for a specific dataset and adjust it, than to figure out complicated if-elif-else stuff in single builder script for all datasets

User is not supposed to figure out the code. He should simply fill out DATASET_CONFIG dict with required params.

**Comment by SpeedOfMagic** [comment]
> This is a step in the right direction I think, but we need to consider this further. This has to cover all the datasets in our benchmark: CoQA, TriviaQA, MMLU, GSM8K, XSum, WMT14, WMT19, claim-level bench.

Done

**Comment by SpeedOfMagic** [comment]
> Next, if we want to use datasets from HF directly, that already have properly formatted input and output, for all of the above (except claim level) we need to consider several versions with different prompts: one for foundation models, and possibly several for verbalized uncertainty estimation for instruct models (see PR https://github.com/IINemo/lm-polygraph/pull/221 for exact prompts).

Added support for instruct datasets.

> Another thing that we have to consider is the need for unprocessed data from the base dataset. I.e. for PTrue, when we want to ask model about the confidence, we better insert original question from TriviaQA, for example, instead of the whole prompt.

I think this needs further discussion and is not required to merge this PR.

Since all points are answered, I'm opening this PR.

**Comment by IINemo** [comment]
I will check it on the weekend

**Comment by yobeen** [comment]
@SpeedOfMagic triviaqa dataset does not contain 'dev' split, please use 'train' for few_shot_dataset_func
https://github.com/IINemo/lm-polygraph/blob/dvasilev-specific-datasets-v2/dataset_builders/polygraph/polygraph.py#L448

**Comment by yobeen** [comment]
# Old and new dataset are matching:

## aeslc
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_aeslc.yaml`

## babiqa
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_babiqa.yaml`

## coqa
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_coqa.yaml`

## gsm8k
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_gsm8k.yaml`

## wmt14_deen
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_wmt14_deen.yaml`

# Old and new dataset are not matching:

## mmlu
Different few-shot sampling between old and new dataset
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_mmlu.yaml`

## trivia_qa
Different few-shot sampling between old and new dataset
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_triviaqa.yaml`

## wiki_bio
- Old dataset: x ends in `":\n"`
- New dataset: x ends in `"\n:\n"`
- Comparing `x[:-2]` vs `x[:-3]`
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_wiki_bio.yaml`
- matches len: 72831
- mismatches len: 0
- partial_matches (x but not y): 0

## xsum
Screenshot_63
Looks like different sampling between old and new dataset, also strangely inconsistent escaping in prompt
Config: `/home/ubuntu/lm-polygraph/examples/configs/polygraph_eval_xsum.yaml`

# New dataset is not loading:

## wmt14_fren
Over 32GB memory required

## wmt19_deen
Over 32GB memory required

**Review by rvashurin — APPROVED** [review]

**Pull request merged**
